/* AUTO-GENERATED by scripts/build-gallery.js. Do not edit by hand. */
window.GALLERY = {
  "categories": [
    {
      "key": "curtains",
      "label": "Curtains",
      "photos": [
        {
          "src": "images/gallery/curtains/PNS_EnterPrises-Curtains6.jpg",
          "title": ""
        },
        {
          "src": "images/gallery/curtains/PNS_EnterPrises-Curtains5.jpg",
          "title": ""
        },
        {
          "src": "images/gallery/curtains/PNS_EnterPrises-Curtains4.jpg",
          "title": ""
        },
        {
          "src": "images/gallery/curtains/PNS_EnterPrises-Curtains3.jpg",
          "title": ""
        },
        {
          "src": "images/gallery/curtains/PNS_EnterPrises-Curtains2.jpg",
          "title": ""
        },
        {
          "src": "images/gallery/curtains/PNS_EnterPrises-Curtains1.jpg",
          "title": ""
        }
      ],
      "videos": []
    },
    {
      "key": "roller",
      "label": "Roller blinds",
      "photos": [
        {
          "src": "images/gallery/roller/PNS_EnterPrises-Roller_Blinds7.jpg",
          "title": ""
        },
        {
          "src": "images/gallery/roller/PNS_EnterPrises-Roller_Blinds6.jpg",
          "title": ""
        },
        {
          "src": "images/gallery/roller/PNS_EnterPrises-Roller_Blinds5.jpg",
          "title": ""
        },
        {
          "src": "images/gallery/roller/PNS_EnterPrises-Roller_Blinds4.jpg",
          "title": ""
        },
        {
          "src": "images/gallery/roller/PNS_EnterPrises-Roller_Blinds3.jpg",
          "title": ""
        },
        {
          "src": "images/gallery/roller/PNS_EnterPrises-Roller_Blinds2.jpg",
          "title": ""
        },
        {
          "src": "images/gallery/roller/PNS_EnterPrises-Roller_Blinds1.jpg",
          "title": ""
        }
      ],
      "videos": []
    },
    {
      "key": "roman",
      "label": "Roman blinds",
      "photos": [
        {
          "src": "images/gallery/roman/PNS_EnterPrises-Roman_Blinds1.jpg",
          "title": ""
        }
      ],
      "videos": []
    },
    {
      "key": "film",
      "label": "Sun control and decorative film",
      "photos": [
        {
          "src": "images/gallery/film/PNS_EnterPrises-Window_Film1.jpg",
          "title": ""
        }
      ],
      "videos": []
    },
    {
      "key": "monsoon",
      "label": "Monsoon",
      "photos": [
        {
          "src": "images/gallery/monsoon/PNS_EnterPrises-Monsoon1.jpg",
          "title": ""
        }
      ],
      "videos": []
    },
    {
      "key": "wooden",
      "label": "Wooden",
      "photos": [
        {
          "src": "images/gallery/wooden/PNS_EnterPrises-Wooden_Blinds5.jpg",
          "title": ""
        },
        {
          "src": "images/gallery/wooden/PNS_EnterPrises-Wooden_Blinds4.jpg",
          "title": ""
        },
        {
          "src": "images/gallery/wooden/PNS_EnterPrises-Wooden_Blinds3.jpg",
          "title": ""
        },
        {
          "src": "images/gallery/wooden/PNS_EnterPrises-Wooden_Blinds2.jpg",
          "title": ""
        },
        {
          "src": "images/gallery/wooden/PNS_EnterPrises-Wooden_Blinds1.jpg",
          "title": ""
        }
      ],
      "videos": []
    }
  ],
  "products": {
    "chick": "images/products/chick.jpg?v=bbf775cb",
    "curtains": "images/products/curtains.jpg?v=a7e146de",
    "film": "images/products/film.jpg?v=0dd435e0",
    "roller": "images/products/roller.jpg?v=09a35d70",
    "roman": "images/products/roman.jpg?v=bd92ba92"
  }
};
